<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>C:\Temp\Poe2DesktopClockBuild\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\Temp\Poe2DesktopClockBuild\msbuild\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
